<?php declare(strict_types = 1);

namespace AppBundle\Repository;

use AppBundle\Entity\League;
use AppBundle\Entity\LeagueHasUser;
use AppBundle\Entity\User;
use AppBundle\Exceptions\SaveEntityFailedException;

use Doctrine\ORM\EntityRepository;

/**
 * LeagueHasUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueHasUserRepository extends EntityRepository
{
    const LEAGUE_LEADER = 1;

    /**
     * @param User $user
     *
     * @return League[]
     */
    public function getLeaguesForUser(User $user)
    {
        $query =  $this->createQueryBuilder('lhu')
            ->andWhere('lhu.isActive = true');

        if (false === $user->hasRole('ROLE_ADMIN')) {
            $query->andWhere('lhu.user = :user')
                ->setParameter('user', $user);
        }

        $leaguesHasUser = $query->getQuery()->getResult();

        $leagues = [];
        /** @var LeagueHasUser $leagueHasUser */
        foreach ($leaguesHasUser as $leagueHasUser) {
            $leagues[] = $leagueHasUser->getLeague();
        }

        return $leagues;
    }

    /**
     * @param LeagueHasUser $leagueHasUser
     *
     * @throws SaveEntityFailedException
     */
    public function save(LeagueHasUser $leagueHasUser)
    {
        try {
            $em = $this->getEntityManager();
            $em->persist($leagueHasUser);
            $em->flush();
        } catch (\Exception $e) {
            throw new SaveEntityFailedException($e->getMessage());
        }
    }

    /**
     * Gets user position
     *
     * @param User $user
     * @param League $league
     *
     * @return int
     */
    public function getPositionForUserInLeague(User $user, League $league)
    {
        $result =  $this->createQueryBuilder('lhu')
            ->select('lhu.position')
            ->andWhere('lhu.user = :user')
            ->andWhere('lhu.league = :league')
            ->andWhere('lhu.isActive = true')
            ->setParameters([
                'user' => $user,
                'league' => $league
            ])
            ->getQuery()
            ->getOneOrNullResult();

        if (null !== $result) {
            return $result['position'];
        }
        return $result;
    }

    /**
     * Get user with the number of points he has
     *
     * @param League $league
     * @return array
     */
    public function getPointsUsersMap(League $league)
    {
        $result =  $this->createQueryBuilder('lhu')
            ->select('lhu.sumOfPoints')
            ->select('lhu.user')
            ->andWhere('lhu.league = :league')
            ->andWhere('lhu.isActive = true')
            ->setParameter('league', $league)
            ->getQuery()
            ->getResult();

        return $result;
    }
}
